# DISCORD BOT TOKEN
token = ""

# presence: bot status, activity which can see in discord
[presence]
    [presence.activity]
    name = ""
    # Activity.type
    # 1: unknown
    # 2: playing
    # 3: streaming
    # 4: listening
    # 5: watching
    # 6: custom
    # 7: competing
    type = 1

    [presence.status]
    # Status
    # 1: online
    # 2: offline
    # 3: idle
    # 5: do not disturb
    # 6: invisible
    type = 1

